version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+pg8000://myuser:isra@localhost/bycatchdb
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
