"""empty message

Revision ID: 0b632bb894dc
Revises: dec3f4850032
Create Date: 2024-12-31 11:19:43.007115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b632bb894dc'
down_revision = 'dec3f4850032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bycatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bpue', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_catch', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bycatch', schema=None) as batch_op:
        batch_op.drop_column('total_catch')
        batch_op.drop_column('bpue')

    # ### end Alembic commands ###
