"""empty message

Revision ID: 7ee9d2f7b02f
Revises: ebf105f95329
Create Date: 2024-12-31 10:57:39.291760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee9d2f7b02f'
down_revision = 'ebf105f95329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'species', ['species_id'], ['species_id'])

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('origin')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
