"""empty message

Revision ID: 8e654b1efa4c
Revises: 7ee9d2f7b02f
Create Date: 2024-12-31 11:03:43.057370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e654b1efa4c'
down_revision = '7ee9d2f7b02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
