"""empty message

Revision ID: abebb637da72
Revises: 0b632bb894dc
Create Date: 2024-12-31 11:23:51.109986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abebb637da72'
down_revision = '0b632bb894dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bycatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear_type', sa.String(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bycatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('gear_type')

    # ### end Alembic commands ###
