"""empty message

Revision ID: d7e7a9b9c1c5
Revises: 33150ff3a1d9
Create Date: 2024-12-29 22:04:20.180865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7e7a9b9c1c5'
down_revision = '33150ff3a1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_bycatch_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bycatch', ['bycatch_id'], ['bycatch_id'])

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('scientific_name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_endangered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_endangered', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scientific_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_bycatch_id_fkey', 'bycatch', ['bycatch_id'], ['bycatch_id'], ondelete='CASCADE')

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
